FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm config set fetch-retries 5 \
 && npm config set fetch-retry-mintimeout 20000 \
 && npm config set fetch-retry-maxtimeout 120000 \
 && npm config set registry https://registry.npmjs.org/ \
 && npm install --legacy-peer-deps --no-audit --no-fund

COPY . .

EXPOSE 5000

CMD ["npm", "start"]
